;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        eval-last-sexp
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-cycle
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        counsel-M-x
        end-of-buffer
        mouse-drag-mode-line
        occur-dwim
        swiper
        ))
